# Generated by Django 5.1.4 on 2024-12-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("teacher", models.CharField(max_length=50)),
            ],
        ),
    ]
